### ISSUE TITLE
Rate and ramp-up generalisation/refactoring + integration with distrib.h

### ISSUE THREAD

**Issue by deRemo** [tomcucinotta/distwalk#56]
The rate parameters are currently only associated to the communication rate between dw_client and dw_node.

The next step is a refactoring of the rate logic to increase its flexibility, the same way the --exp --ea parameters have been deprecated in favor of `pd` (distrib.h).  For instance, we should be capable of tuning the disk read/write rate as well, in a similar matter (i.e., specify a starting rate, a delta, and a stopping rate)

On a similar note, the `pd` structure should be integrated within the rate logic:
```
./dw_client --rate seq:min=10,delta=5,delta=50 -S 200 --store-offset seq:min=1000,delta=200,max=2000 -n 100
```
Meaning that 100 store requests are sent with a ramping-up rate, both in terms of reqs/s and bytes/s

**Comment by tomcucinotta** [comment]
It should all be there in the latest commits, the new syntax has `...,step=` instead of `...,delta=`, it supports also a column specifier for CSV files with the `--rate=file:/path/to/file,col=col_id` syntax, and also a `-n auto` option for the automatic computation of the number of packets, when it is possible (--rate=seq: or file: only).
We can close after a review of the changes.
